// CreatedDecks.js
import React, { useState, useEffect } from "react";
import db from "../firebase"; // Adjust the path if necessary
import {
  collection,
  getDocs,
  deleteDoc,
  doc,
  query,
  orderBy,
} from "firebase/firestore";
import { Link } from "react-router-dom";

const CreatedDecks = ({ setDecks, decks }) => {
  useEffect(() => {
    const fetchDecks = async () => {
      try {
        const querySnapshot = await getDocs(
          query(collection(db, "decks"), orderBy("name", "asc"))
        );
        const decksArray = [];
        querySnapshot.forEach((doc) => {
          decksArray.push({ id: doc.id, ...doc.data() });
        });
        setDecks(decksArray);
      } catch (error) {
        console.error("Error fetching decks: ", error);
      }
    };

    fetchDecks();
  }, [setDecks]);

  const removeDeck = async (deckId) => {
    try {
      // Delete the deck from Firestore
      await deleteDoc(doc(db, "decks", deckId));

      // Filter out the removed deck from the local state
      const updatedDecks = decks.filter((deck) => deck.id !== deckId);
      setDecks(updatedDecks);
    } catch (error) {
      console.error("Error removing deck: ", error);
    }
  };

  if (!decks) {
    return <div className="created-decks">Loading decks...</div>;
  }

  return (
    <div className="created-decks">
      <h2 className="category">Decks generated by Aethermind</h2>
      <ul>
        {decks.map((deck) => (
          <li key={deck.id} className="card-item">
            <Link to={`/deck/${deck.id}`}>{deck.name}</Link>
            {/* <button
              className="delete-button"
              onClick={() => removeDeck(deck.id)}
            ></button> */}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default CreatedDecks;
